variables:
  REPO_URL: 'packages.opentap.io'
  DOCKER_REGISTRY: 'registry.gitlab.com'

stages:
#  - docs
  - build
  - tests
  - publish

#Documentation:
#  stage: docs
#  image: $DOCKER_REGISTRY/opentap/buildrunners/documentationgeneration:latest
#  tags: [ docker, gce ]
#  script:
#    - tap generate-chm "Documentation/Help/Readme.md" --out "ResultsAndTiming/DemonstrationHelp.chm" --title "TAP Demonstration Plugin Package Help" --startpage "Documentation/Help/Welcome/Readme.md"
#  artifacts:
#    expire_in: 1 week
#    paths:
#       - "ResultsAndTiming/*.chm"

# build

Build:
  stage: build
  image: opentapio/opentap:9.5-ubuntu18.04
  tags: [ docker, gce ]
  script: 
    - dotnet restore
    - dotnet publish -c Release
    - mv bin/Release/*.TapPackage .
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
       - "*.TapPackage"


Package-Test:
  stage: tests
  image: opentapio/opentap:9.5-ubuntu18.04
  tags: [ docker, gce ]
  dependencies:
    - Build
  script:
    - cp Demonstration.*.TapPackage DemonstrationTest.TapPackage
    - tap package install DemonstrationTest.TapPackage --force    
    - tap package test Demonstration -v

TestPlan-Test:
  stage: tests
  image: opentapio/opentap:9.5-ubuntu18.04
  tags: [ docker, gce ]
  dependencies:
    - Build
  script:
    - cp Demonstration.*.TapPackage DemonstrationTest.TapPackage    
    - tap package install DemonstrationTest.TapPackage --force
    - cd /opt/tap
    - tap run Packages/Demonstration/DataGenForResultsViewer.TapPlan
    - tap run Packages/Demonstration/DataGenForTimingAnalysis.TapPlan --settings "Tests/Test Bench Profile"
    - tap run Packages/Demonstration/DataGenForTimingAnalysisParallel.TapPlan --settings "Tests/Test Bench Profile"

# auto publish from release9x
AutoPublish (Internal Repo):
  stage: publish
  only:
     - release9x
  dependencies:
     - Build
  script:
    - tap package install -f -r "$REPO_URL" PackagePublishAction --version beta
    - tap package publish -r "$REPO_URL" -p Demonstration -k "$REPO_PUBLISH_KEY" *.TapPackage

# manual publish
ManualPublish (External Repo):
  stage: publish
  when: manual
  dependencies:
     - Build
  script: 
    - tap package install -f -r "$REPO_URL" PackagePublishAction --version beta
    - tap package publish -r "$REPO_URL" -p Demonstration -k "$REPO_PUBLISH_KEY" *.TapPackage
