<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <UseWPF>True</UseWPF>
        <EnableWindowsTargeting>True</EnableWindowsTargeting>
        <EditorVersion>9.31.0+db7205e3</EditorVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="OpenTAP" Version="$(OpenTapVersion)" />
        <OpenTapPackageReference Include="OpenTAP" />
        <OpenTapPackageReference Include="Editor" Version="$(EditorVersion)"/>
        <OpenTapPackageReference Include="WPF Controls" Version="$(EditorVersion)"/>
        <OpenTapPackageReference Include="Results Viewer" Version="$(EditorVersion)"/>
        <OpenTapPackageReference Include="CSV" Version="9.14.2+44a9bac5"/>
        <OpenTapPackageReference Include="SQLite and PostgreSQL" Version="9.6.0+558afbf4"/>
        <OpenTapPackageReference Include="Live Results Panel" Version="1.2.0+361617d6"/>
        <OpenTapPackageReference Include="Metrics and Assets Panel" Version="1.2.0+361617d6"/>

    </ItemGroup>
    <ItemGroup>
      <Resource Include="Resources\batterydemo.png" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Battery\OpenTap.Plugins.Demo.Battery.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Update="Resources\battery_demo.TapReport">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
          <Link>Packages/Demonstration/battery_demo.TapReport</Link>
      </None>
        <None Update="Resources\battery_demo_preset.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Packages/Demonstration/battery_demo_preset.xml</Link>
        </None>
    </ItemGroup>

</Project>
